name: emi_manager
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.2.6

dependencies:
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: null
  go_router: null
  hive_flutter: null
  intl: null
  onboarding: ^4.0.2
  riverpod_annotation: null
  uuid: null
  collection: ^1.17.0
  showcaseview: ^3.0.0

dev_dependencies:
  build_runner: null
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: null
  hive_generator: null
  riverpod_generator: null

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/