name: emi_manager
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  go_router:
  flutter_riverpod:
  riverpod_annotation:
  intl:
  hive_flutter:
  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  build_runner:
  go_router_builder:
  riverpod_generator:
  hive_generator:

flutter:
  generate: true
  uses-material-design: true
